server:
  port: 8090

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
  application:
    name: iam-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/iam_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
  mail:
    host: mailhog
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          physical-strategy: com.example.iam.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
  cloud:
    stream:
      bindings:
        userCreatedEvent-out-0:
          destination: user-events
          content-type: application/json
          binder: rabbit
        userUpdatedEvent-out-0:
          destination: user-update-events
          content-type: application/json
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_HOST:rabbitmq}
                port: ${RABBITMQ_PORT:5672}
                username: ${RABBITMQ_DEFAULT_USER:guest}
                password: ${RABBITMQ_DEFAULT_PASS:guest}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: iam-service

authorization:
  jwt:
    secret: ${JWT_SECRET:ChangeThisToA32CharOrMoreSecretValue_1234567890}
    expiration:
      days: 7

app:
  frontend:
    base-url: http://localhost:8081

iam:
  superadmin:
    username: ${IAM_ADMIN_USERNAME:${SUPERADMIN_USERNAME:superadmin}}
    email: ${IAM_ADMIN_EMAIL:${SUPERADMIN_EMAIL:superadmin@example.com}}
    password: ${IAM_ADMIN_PASSWORD:${SUPERADMIN_PASSWORD:ChangeMe_Admin!123}}

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    stream:
      rabbit:
        binder:
          connection-timeout: 30000
          requested-heartbeat: 30
      binders:
        rabbit:
          environment:
            spring:
              rabbitmq:
                connection-timeout: 30000
                requested-heartbeat: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    rabbit:
      enabled: true
# --- Added by terminal patch: dev schema management ---
spring.jpa.hibernate.ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG
