server:
  port: 9090

spring:
  application:
    name: profiles-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/profiles_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_ROOT_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          physical-strategy: com.profiles.service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
  cloud:
    function:
      definition: userCreated
    stream:
      bindings:
        userCreated-in-0:
          destination: user-events
          content-type: application/json
          group: profiles-service-group
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_HOST:rabbitmq}
                port: ${RABBITMQ_PORT:5672}
                username: ${RABBITMQ_DEFAULT_USER:guest}
                password: ${RABBITMQ_DEFAULT_PASS:guest}


eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: profiles-service

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    stream:
      rabbit:
        binder:
          connection-timeout: 30000
          requested-heartbeat: 30
      binders:
        rabbit:
          environment:
            spring:
              rabbitmq:
                connection-timeout: 30000
                requested-heartbeat: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    rabbit:
      enabled: true
